In [1]:
import pandas as pd

In [2]:
mloc_orig_df = pd.read_hdf('merged.h5')

In [3]:
mloc_orig_df.shape

(389396, 15)

In [4]:
mloc_orig_df.describe()

,pressure,relative_humidity,temperature,wind_direction,wind_speed,o(I)_I,r0_day,solar_zenith_angle,r0_night,Cn2,r0,r0_day_10T,r0_night_10T,Cn2_10T,r0_10T
count,357159.000000,339861.000000,339862.000000,357169.000000,357183.000000,77708.000000,77708.000000,262023.000000,51658.000000,2.360280e+05,129366.000000,72235.000000,53300.000000,2.371150e+05,125535.000000
mean,774.640413,35.550712,11.022863,190.880429,2.306235,0.001410,3.608049,87.303277,7.336046,1.639802e-15,5.096700,3.579578,7.336219,1.627435e-15,5.174583
std,4.563120,24.213644,8.004922,80.564335,1.695936,0.000479,2.530093,38.827636,2.491211,1.856607e-15,3.107570,1.985577,2.438668,1.815265e-15,2.870790
min,752.100000,1.000000,-13.000000,3.750000,0.100000,0.000103,0.821452,10.946529,2.367400,2.316900e-18,0.821452,0.876854,2.376300,2.408850e-18,0.876854
25%,772.100000,19.000000,5.400000,142.500000,1.190000,0.001097,2.285307,56.150933,5.526900,3.239275e-16,2.686307,2.367127,5.549150,3.289575e-16,2.776279
50%,775.300000,29.000000,11.100000,187.350000,1.835000,0.001381,2.938013,85.335723,7.075500,1.014500e-15,4.264792,2.972896,7.075500,1.022065e-15,4.437734
75%,778.000000,45.000000,17.400000,254.300000,2.850000,0.001652,4.101076,120.016918,8.891100,2.326725e-15,6.933100,4.096545,8.868850,2.317525e-15,7.031000
max,785.600000,110.000000,31.500000,358.250000,20.285000,0.003500,81.041189,169.051816,23.229000,1.960600e-14,81.041189,49.948156,22.076450,1.941150e-14,49.948156

In [ ]:
# shampoo_extracted_df['label']

In [ ]:
# shampoo_stats_df = shampoo_extracted_df.describe()

In [ ]:
# shampoo_stats_df.loc['std',shampoo_stats_df.loc['std'] != 0].count()

In [ ]:
# shampoo_stats_df.loc['std',shampoo_stats_df.loc['std'] != 0]